[platformio]
default_envs = greenhouse_controller

[env:greenhouse_controller]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
    -D CORE_DEBUG_LEVEL=3
lib_deps =
    adafruit/Adafruit BME280 Library@^2.3.0
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit SSD1306@^2.5.11
    claws/BH1750@^1.3.0
    madhephaestus/ESP32Servo@^3.0.6
    milesburton/DallasTemperature@^4.0.4
    paulstoffregen/OneWire@^2.3.8
    knolleary/PubSubClient@^2.8

[env:control_logic_native]
platform = native
test_build_src = no
build_flags =
    -std=gnu++17
